services:
  papermc:
    build:
      context: .
      args:
        paper_version: 1.20.4
        paper_build: 460
        servinator_version: 1.0.0
      target: release
    environment:
      JAVA_TOOL_OPTIONS: '-Xmx4G -Xms4G'
    ports:
      - 0.0.0.0:25565:25565
    stdin_open: true
    #tty: true
    #volumes:
    #  - ./data:/home/paper/
