services:
  papermc:
    build:
      context: .
      args:
        version: 1.20.4
        build: 450
      target: release
    environment:
      JAVA_TOOL_OPTIONS: '-Xmx4G -Xms4G'
    ports:
      - 0.0.0.0:25565:25565
    stdin_open: true
    tty: true
    #volumes:
    #  - ./data:/usr/local/papermc/
