name: Docker Image CI

on:
  push:
    branches: [main]
  schedule:
    - cron: '25 4 * * *'
  workflow_dispatch:

jobs:

  # if triggered by schedule, determine if a new release is needed. 
  check-schedule:

    runs-on: ubuntu-latest
    
    env:
      PAPER_VERSION: 1.21.1
      
    outputs:
      IMAGE_TAG: ${{ steps.set-env.outputs.IMAGE_TAG }}
      PAPER_VERSION: ${{ env.PAPER_VERSION }}
      PAPER_BUILD: ${{ steps.set-env.outputs.PAPER_BUILD }}

    steps:
      - uses: actions/checkout@v4 
      
      - name: check if triggered by schedule, set env
        id: set-env
        run: | 
          paper_latest_build=$(./get-papermc-latest-build.sh "${{ env.PAPER_VERSION }}")

          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            # check if new build should be created
            latest_tag=$(echo $(curl -s "https://api.github.com/repos/sharp378/PaperMC/releases/latest" | jq -r '.tag_name'))
            build=$(echo $latest_tag | cut -d '-' -f 2)
            if [ $paper_latest_build -eq $build ]; then
              echo "No new PaperMC builds at this time"
              exit 0
            fi
          fi

          echo "IMAGE_TAG=${{ env.PAPER_VERSION }}-${paper_latest_build}" >> "$GITHUB_OUTPUT"
          echo "PAPER_BUILD=${paper_latest_build}" >> "$GITHUB_OUTPUT"

  build:
    
    needs: check-schedule

    if: ${{ needs.check-schedule.outputs.IMAGE_TAG != '' }}
  
    runs-on: ubuntu-latest
    
    env:
      DOCKERHUB_REPO: sharpscontainer/paper-mc
      IMAGE_TAG: ${{ needs.check-schedule.outputs.IMAGE_TAG }}
      PAPER_BUILD: ${{ needs.check-schedule.outputs.PAPER_BUILD }}
      PAPER_VERSION: ${{ needs.check-schedule.outputs.PAPER_VERSION }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set env
        run : |
          servinator_version=$(./get-servinator-latest-version.sh)
          echo "SERVINATOR_VERSION=${servinator_version}" >> $GITHUB_ENV
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            paper_version=${{ env.PAPER_VERSION }}
            paper_build=${{ env.PAPER_BUILD }}
            servinator_version=${{ env.SERVINATOR_VERSION }}
          target: release
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_REPO }}:latest

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.IMAGE_TAG }}
          allowUpdates: true
          
