name: Docker Image CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKERHUB_REPO: sharpscontainer/paper-mc
      PAPER_VERSION: 1.20.4

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: |
          build=$(./get-papermc-latest-build.sh "${{ env.PAPER_VERSION }}")
          echo "IMAGE_TAG=${{ env.PAPER_VERSION }}-${build}" >> $GITHUB_ENV 
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: version=${{ env.PAPER_VERSION }},build=
          target: release
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
          
