name: Docker Image CI

on:
  push:
    branches: [main]
  schedule:
    - cron: '25 4 * * *'
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKERHUB_REPO: sharpscontainer/paper-mc
      PAPER_VERSION: 1.20.4

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4 
      
      - name: check if triggered by schedule, set env
        run: | 
          paper_latest_build=$(./get-papermc-latest-build.sh "${{ env.PAPER_VERSION }}")

          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            # check if new build should be created
            latest_tag=$(git describe --tags --abbrev=0)
            build=$(echo $latest_tag | cut -d '-' -f 2)
            if [ $paper_latest_build -eq $build ]; then
              echo "No new PaperMC builds at this time"
              exit 1;
            fi
          fi

          servinator_version=$(./get-servinator-latest-version.sh)
          echo "PAPER_BUILD=${paper_latest_build}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ env.PAPER_VERSION }}-${paper_latest_build}" >> $GITHUB_ENV 
          echo "SERVINATOR_VERSION=${servinator_version}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set env
        run: |
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            paper_version=${{ env.PAPER_VERSION }}
            paper_build=${{ env.PAPER_BUILD }}
            servinator_version=${{ env.SERVINATOR_VERSION }}
          target: release
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKERHUB_REPO }}:latest

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.IMAGE_TAG }}
          generateReleaseNotes: true
          allowUpdates: true
          
